title = "hey world"
languageCode = "en-us"
baseURL = "https://heyhx.xyz/"
theme = "archie"


[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=true # don't use CDNs for fonts and icons, instead serve them locally.
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20

