baseURL = 'https://heyhx.xyz/'
languageCode = 'en-us'
title = 'Hey World'

theme = "typo"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Tech Blog"


# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Collection to display on home
homeCollectionTitle = 'About'
homeCollection = 'about'

# Lists parameters
paginationSize = 10
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/user/"

[[params.social]]
name = "medium"
url = "https://medium.com/@user"

[[params.social]]
name = "github"
url = "https://github.com/user"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'
